image: node:14.17.6

pipelines:
  default:
    - step:
        name: Build React
        deployment: production
        script:
          - yarn install
          - yarn build
    - step:
        name: Deploy to Firebase
        deployment: production
        script:
          - pipe: atlassian/firebase-deploy:0.2.1
            variables:
              FIREBASE_TOKEN: $FIREBASE_TOKEN
              PROJECT_ID: $FIREBASE_PROJECT
